#!/usr/bin/env bash
# setup.sh — Prepare the Docker-based local multi-node SSH test environment.
#
# Usage:
#   ./docker/setup.sh          # spin up test nodes
#   ./docker/setup.sh --down   # tear down test nodes

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_DIR="$SCRIPT_DIR/ssh"
KEY_FILE="$SSH_DIR/id_ed25519"
SSH_CONFIG_FILE="$SSH_DIR/ssh.config"

# ── Tear-down mode ──────────────────────────────────────────────────────────
if [[ "${1:-}" == "--down" ]]; then
    echo "🛑 Stopping Docker test nodes..."
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" down
    echo "✅ Test nodes stopped."
    exit 0
fi

# ── Generate test SSH key pair ───────────────────────────────────────────────
if [ ! -f "$KEY_FILE" ]; then
    echo "🔑 Generating test SSH key pair (saved in docker/ssh/)..."
    mkdir -p "$SSH_DIR"
    # No passphrase (-N "") is intentional: this key is only used for
    # automated local testing inside Docker and must never be reused in
    # production or against real machines.
    ssh-keygen -t ed25519 -f "$KEY_FILE" -N "" -C "petal-test-key" -q
    echo "✅ Key pair generated."
else
    echo "ℹ️  Test key pair already exists at $KEY_FILE"
fi

# ── Write SSH config snippet ─────────────────────────────────────────────────
cat > "$SSH_CONFIG_FILE" << EOF
# Petal Docker test nodes — generated by docker/setup.sh
# Include this file or paste it into ~/.ssh/config

Host node1
    HostName 127.0.0.1
    Port 2221
    User petal
    IdentityFile $KEY_FILE
    # StrictHostKeyChecking/UserKnownHostsFile are relaxed intentionally —
    # these containers are ephemeral local test nodes only.
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

Host node2
    HostName 127.0.0.1
    Port 2222
    User petal
    IdentityFile $KEY_FILE
    # StrictHostKeyChecking/UserKnownHostsFile are relaxed intentionally —
    # these containers are ephemeral local test nodes only.
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

Host node3
    HostName 127.0.0.1
    Port 2223
    User petal
    IdentityFile $KEY_FILE
    # StrictHostKeyChecking/UserKnownHostsFile are relaxed intentionally —
    # these containers are ephemeral local test nodes only.
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOF

# ── Build and start containers ───────────────────────────────────────────────
echo "🐳 Building and starting Docker test nodes..."
docker compose -f "$SCRIPT_DIR/docker-compose.yml" up --build -d

# ── Wait for SSH services to become ready ───────────────────────────────────
echo "⏳ Waiting for SSH services to be ready..."
MAX_RETRIES=15
for port in 2221 2222 2223; do
    retries=0
    until ssh -p "$port" -i "$KEY_FILE" \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o ConnectTimeout=2 \
              petal@127.0.0.1 true 2>/dev/null; do
        retries=$((retries + 1))
        if [ "$retries" -ge "$MAX_RETRIES" ]; then
            echo "❌ Timed out waiting for SSH on port $port"
            exit 1
        fi
        sleep 1
    done
    echo "  ✔  node on port $port is ready"
done

# ── Install SSH config ───────────────────────────────────────────────────────
SSHCONFIG=~/.ssh/config
MARKER="# BEGIN petal-docker-test"
ENDMARKER="# END petal-docker-test"

mkdir -p ~/.ssh
if grep -q "$MARKER" "$SSHCONFIG" 2>/dev/null; then
    echo "ℹ️  SSH config already contains Petal Docker entries — skipping."
else
    {
        echo ""
        echo "$MARKER"
        cat "$SSH_CONFIG_FILE"
        echo "$ENDMARKER"
    } >> "$SSHCONFIG"
    echo "✅ SSH config entries added to $SSHCONFIG"
fi

echo ""
echo "🚀 All nodes are up! Run tasks with:"
echo "   ./petal -f docker/task.yml"
echo "   ./petal -f docker/task.yml ping-all"
